### ISSUE TITLE
World doesn't load after upgrading the Modpack

### ISSUE THREAD

**Issue by daveppeters** [vizthex123/viz-projects#1]
**Modpack Version:**  4.0

**Description of issue:** I upgraded the modpack to a new profile, then copied my save folder and journeymap folder into the new instances. When I try to load the world it just sits on the loading screen forever until I stop javaw.exe from task manager, and at that point it gives Exit Code 1

**Steps to reproduce, if applicable:** I can provide my save file

[latest.log](https://github.com/user-attachments/files/17625583/latest.log)

**Comment by vizthex123** [comment]
Looks like it got stuck loading because of the amount of mods I removed. Seems like Forge was having trouble deleting all the old blocks.

Send me the world and I'll see if I can fix it.

**Comment by vizthex123** [comment]
Yeah, it looks like an unfixable Forge issue.

My dev instance has stopped working (again), but I did attempt to fix this and couldn't find any solutions.

Download the [quests](https://github.com/vizthex123/viz-projects/blob/main/archived/teoe/teoe_quests.zip) and extract them to the `config` folder (overriding the `hqm` folder that's already there), that way you'll get the updated & fixed versions.

And if I can ever update the pack again, make sure to download all of the [scripts](https://github.com/vizthex123/viz-projects/tree/main/archived/teoe/scripts) so you can get the updated recipes - again, overriding the default ones (located in the `scripts` folder in the main directory - same place you find `mods` and `config`)

**Comment by daveppeters** [comment]
What if I delete the mods one at a time and restart the world after each
deletion? Once they are all deleted, I can switch to the 4.0 version and
hopefully it will load. Can you give a list of all the mods you deleted?

Alternatively, could it be because some of the blocks are in my ME system?
Do I need to take them out? Is there a way to search a mod within the ME
system?

Thanks

**Comment by vizthex123** [comment]
They're listed at the bottom of the changelog. AE2 should just read & delete the invalid NBT data, but you can remove them from the system beforehand (no reason not to try it out, after all).

You can try that though. Might fix it.
